### ISSUE TITLE
ImportError: cannot import name 'Fragment'

### ISSUE THREAD

**Issue by derpadoo** [Cymmetria/ciscoasa_honeypot#1]
Using Python 3.6.4

```bash
$ pip freeze
asn1crypto==0.24.0
cffi==1.11.4
cryptography==2.1.4
idna==2.6
ike==0.1.1
pkg-resources==0.0.0
pyasn1==0.4.2
pycparser==2.18
rsa==3.4.2
six==1.11.0
```

```bash
$ python asa_server.py
Traceback (most recent call last):
  File "asa_server.py", line 13, in <module>
    import ike_server
  File "/home/user/ciscoasa_honeypot/ike_server.py", line 5, in <module>
    from ike.payloads import Fragment
ImportError: cannot import name 'Fragment'
```

**Comment by paralax** [comment]
i ran into this too. i had to import the `vendor_fragment` branch of the `ike` repo, but that didn't work right either. i have a PR open in that `ike` branch to fix the `setup.py` call, but then it's failing at run time - the util subdir doesn't get installed. 

i made some more notes in #3

**Comment by dekelb** [comment]
There is an IKE fork here: https://github.com/Cymmetria/ike/tree/vendor_fragment which should have fix these problems. Did you try to use that specific fork of the lib?

**Comment by omercnet** [comment]
fixed master branch on https://github.com/Cymmetria/ike - try again
