### ISSUE TITLE
Please add hpfeeds support

### ISSUE THREAD

**Issue by jjjan** [Cymmetria/ciscoasa_honeypot#8]
Hello, could you add hpfeeds support for this honeypoot?

**Comment by omercnet** [comment]
@jjjan this honeypot is not built with extensibility in mind, but https://github.com/Cymmetria/honeycomb is and we'll be adding this cisco_asa service to it soon, as well as hpfeeds (you're welcome to open an issue there)

check it out and let us know what you think!
